apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mysql-binding
spec:
  type: bindings.mysql
  version: v1
  metadata:
    - name: url # Required, define DB connection in DSN format
      value: "java_app:pass@tcp(localhost:3306)/dapr_ked"