apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mysql-statestore
spec:
  type: state.mysql
  version: v1
  metadata:
    - name: connectionString
      value: "java_app:pass@tcp(localhost:3306)/?allowNativePasswords=true"
    - name: schemaName
      value: "dapr_ked"